<?php
/* @var \Magestore\Bannerslider\Block\SliderItem $block */
$styleSlide = $block->getSlider()->getStyleSlide();
$slider = $block->getSlider();
$htmlId   = $block->getFlexsliderHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magestore_Bannerslider::css/shop.css')?>">
<div class="pc2015-main-slider">

    <ul class="pc2015-main-slider-header pc2015-clearfix">
        <?php foreach ($bannerCollection as $banner) :?>
        <li>
            <div id="main<?php echo $banner->getId() ?>" align="center"><a href="#"><?php echo $banner->getName() ?></a></div>
        </li>
        <?php endforeach;?>
    </ul>

    <div class="pc2015-main-slider-body">
        <ul>
            <?php foreach ($bannerCollection as $banner) :?>
            <li>
                <div id="list<?php echo $banner->getId() ?>">
                    <a href="<?php echo $banner->getClickUrl() ?>" target="<?php echo $banner->getTargetValue() ?>" >
                        <img src="<?php echo $block->getBannerImageUrl($banner) ?>" alt="<?php echo $banner->getImageAlt() ?>" width="766" height="243">
                    </a>
                </div>
            </li>
            <?php endforeach;?>
        </ul>
    </div>

</div>


<script>
    require([ 'jquery', 'jcarouselx'], function($){
        var sliderButton = '<a href="#" class="pc2015-designed"></a>';

        function setupSlider(jq) {
            var slider = {
                base: jq,
                headers: jq.find('.pc2015-main-slider-header > li'),
                items: jq.find('.pc2015-main-slider-body > ul > li'),
                slider: jq.find('.pc2015-main-slider-body')
            };
            slider.slider.jcarousel({
                scroll: 1,
                auto: 10,
                wrap: 'circular',
                buttonPrevHTML: sliderButton,
                buttonNextHTML: sliderButton,
                setupCallback: function() {
                    slider.slider.find('.jcarousel-prev,.jcarousel-next').bind('click', function() {
                        return false;
                    });
                    updateSliderHeader(slider, 0);
                },
                itemFirstInCallback: {
                    onBeforeAnimation: function(jc, li) {
//                        if (pc2015.isIE7) {
//                            li = $(li);
//                            var a = $(li).find('a');
//                            if (a.length === 0) {
//                                a = slider.items.eq((jc.first - 1) % slider.headers.length).find('a').clone(false);
//                                li.append(a);
//                            }
//                        }
                    },
                    onAfterAnimation: function(jc, li) {
                        updateSliderHeader(slider, jc.first - 1);
                    }
                }
            });
            slider.headers.each(function(i) {
                $('a', this).bind('click', function() {
                    slider.slider.data('jcarousel').scroll(i + 1);
                    return false;
                });
            });
        }

        $('.pc2015-main-slider').each(function() {
            setupSlider($(this));
        });

        $('.pc2015-item,.pc2015-cart-item').each(function() {
            setupCartItem($(this));
        });

        $('.pc2015-main-block').each(function() {
            setupMainBlock($(this));
        });

        $('.pc2015-item-carousel').each(function() {
            setupItemCarousel($(this));
        });

        function updateSliderHeader(slider, i) {
            var headers = slider.headers;
            headers.removeClass('pc2015-active').eq(i % headers.length).addClass('pc2015-active');
        }

        function setupCartItem(jq, noMember) {
            var quantityJq = jq.find('.pc2015-cart-quantity');
            jq.find('.pc2015-cart-inc').bind('click', function() {
                if (!noMember && !$(this).hasClass('pc2015-disabled')) {
                    updateCartItem(quantityJq, (quantityJq.text() | 0) + 1);
                }
                return false;
            });
            jq.find('.pc2015-cart-dec').bind('click', function() {
                if (!noMember && !$(this).hasClass('pc2015-disabled')) {
                    updateCartItem(quantityJq, (quantityJq.text() | 0) - 1);
                }
                return false;
            });
            jq.find('.pc2015-cart-memo').bind('click', function() {
                return false;
            });
            jq.find('.pc2015-cart-delete').bind('click', function() {
                return false;
            });
        }

        function updateCartItem(jq, quantity) {
            quantity = quantity | 0;
            if (quantity < 1) {
                quantity = 1;
            } else if (quantity > 99) {
                quantity = 99;
            }
            jq.text(quantity);
            return quantity;
        }

        function setupMainBlock(jq) {
            var block = {
                block: jq,
                header: jq.find('.pc2015-main-block-header'),
                body: jq.find('.pc2015-main-block-body'),
                visible: !jq.hasClass('pc2015-main-block-hide'),
                button: jq.find('a.pc2015-main-block-toggle')
            };
            block.button.bind('click', function() {
                if (block.visible) {
                    collapseMainBlock(block);
                } else {
                    expandMainBlock(block);
                }
                return false;
            });
            if (block.block.hasClass('pc2015-main-block-closed')) {
                collapseMainBlock(block, true);
            }
        }

        function expandMainBlock(block, noAnimation) {
            block.visible = true;
            block.body.stop(true, true).slideDown(noAnimation ? 0 : 300, function() {
//                if (pc2015.isIE7) {
//                    block.body.find('.pc2015-center-image').each(function() {
//                        adjustCenterImageIE7($(this));
//                    });
//                }
                block.block.removeClass('pc2015-main-block-hide');
            });
        }

        function collapseMainBlock(block, noAnimation) {
            block.visible = false;
            block.body.stop(true, true).slideUp(noAnimation ? 0 : 300, function() {
                block.block.addClass('pc2015-main-block-hide');
            });
        }

        function setupItemCarousel(jq) {
            var items = jq.find('.pc2015-item');
            var itemCarousel = {
                itemCarousel: jq,
                count: items.length
            };
            var heightsList = [];
            if (jq.hasClass('pc2015-item-list-selectable')) {
                items.each(function(i) {
                    heightsList.push(getItemHeights($(this), true));
                });
                adjustSelectableItemHeight(heightsList);
            } else {
                items.each(function(i) {
                    heightsList.push(getItemHeights($(this)));
                });
                adjustItemHeight(heightsList);
            }
            itemCarousel.itemCarousel.jcarousel({
                scroll: 1,
                setupCallback: function(jc) {
                    jc.buttonNext.bind('click', function() {
                        return false;
                    });
                    jc.buttonPrev.bind('click', function() {
                        return false;
                    });
                }
            });
//            pc2015.$win.bind('resize', $.debounce(500, function() {
//                adjustItemCarousel(itemCarousel);
//            }));
            adjustItemCarousel(itemCarousel);
        }

        function adjustItemCarousel(itemCarousel) {
            var w0 = itemCarousel.itemCarousel.parent().width();
            var w = 717;
            var max = 4;
            var jc = itemCarousel.itemCarousel.data('jcarousel');
            while (w + 60 + 182 < w0) {
                w += 182;
                ++max;
            }
            if (itemCarousel.itemCarousel.width() !== w) {
                itemCarousel.itemCarousel.width(w);
                jc.scroll(1);
            }
            if (itemCarousel.count <= max) {
                jc.buttonNext.hide();
                jc.buttonPrev.hide();
            } else {
                jc.buttonNext.show();
                jc.buttonPrev.show();
            }
        }

        function getItemHeights(item, forSelectable) {
            var name1 = item.find('.pc2015-item-name');
            var name2 = item.find('.pc2015-item-variation');
            var name3 = item.find('.pc2015-item-catalog-price');
            var price = item.find('.pc2015-item-price');
            var price1 = price.eq(0);
            var price2 = price.eq(1);
            if (price.length === 1) {
                price2 = null;
            }
            var sku = item.find('.pc2015-item-sku');
            var inner = item.find('.pc2015-item-inner');
            var select = item.find('.pc2015-item-select');
            var heights = {
                name: 0,
                nameBottom: 0,
                price: 0,
                sku: 0
            };
            if (forSelectable) {
                sku.css({
                    paddingBottom: 6,
                    marginBottom: 0,
                    borderBottomWidth: 0
                });
                select.css({
                    marginBottom: 0
                });
                inner.css({
                    paddingBottom: 0,
                    marginBottom: 0,
                    borderBottomWidth: 0
                });
            } else {
                price1.css({
                    paddingTop: 0
                });
                price.last().css({
                    paddingBottom: 0,
                    marginBottom: 6
                });
            }
            if (name1.length > 0) {
                heights.name += name1.height() + 18 + 8;
                heights.nameBottom = 8;
            }
            if (name2.length > 0) {
                heights.name += name2.height() + 6;
                heights.nameBottom = 6;
            }
            if (name3.length > 0) {
                heights.name += name3.height() + 6;
                heights.nameBottom = 6;
            }
            if (price1.length > 0) {
                heights.price += price1.height();
            }
            if (price2) {
                heights.price += price2.height() + 6;
            }
            if (sku.length > 0) {
                heights.sku += sku.innerHeight();
            }
            return {
                items: {
                    price1: price1,
                    price: price,
                    sku: sku,
                    inner: inner,
                    select: select,
                    quantity: item.find('.pc2015-item-quantity')
                },
                heights: heights
            };
        }
        function adjustItemHeight(list) {
            var items, heights;
            var name = 0;
            var price = 0;
            var sku = 0;
            for (var l = list.length, i = 0; i < l; ++i) {
                heights = list[i].heights;
                name = Math.max(heights.name, name);
                price = Math.max(heights.price, price);
                sku = Math.max(heights.sku, sku);
            }
            for (i = 0; i < l; ++i) {
                items = list[i].items;
                heights = list[i].heights;
                items.price1.css({
                    paddingTop: name - heights.name
                });
                items.price.last().css({
                    paddingBottom: price - heights.price
                });
                if (items.quantity.length === 0) {
                    items.price.last().css({
                        marginBottom: 59
                    });
                }
            }
        }

        function adjustSelectableItemHeight(list) {
            var items, heights;
            var name = 0;
            var price = 0;
            var sku = 0;
            for (var l = list.length, i = 0; i < l; ++i) {
                heights = list[i].heights;
                name = Math.max(heights.name, name);
                price = Math.max(heights.price, price);
                sku = Math.max(heights.sku, sku);
            }
            for (i = 0; i < l; ++i) {
                items = list[i].items;
                heights = list[i].heights;
                items.price1.css({
                    marginTop: name - heights.name + heights.nameBottom,
                    paddingBottom: price - heights.price
                });
                if (items.sku.length > 0) {
                    if (items.select.length > 0) {
                        items.sku.css({
                            paddingBottom: sku - heights.sku + 6
                        });
                        if (items.quantity.length === 0) {
                            items.select.css({
                                marginBottom: 58
                            });
                        }
                    } else {
                        if (items.quantity.length > 0) {
                            items.sku.css({
                                paddingBottom: sku - heights.sku + 6 + 25,
                                borderBottomWidth: 1
                            });
                        } else {
                            items.sku.css({
                                paddingBottom: sku - heights.sku + 6 + 25 + 51,
                                borderBottomWidth: 1
                            });
                            items.sku.css({
                                marginBottom: 7
                            });
                        }
                    }
                } else {
                    if (items.select.length > 0) {
                        items.inner.css({
                            paddingBottom: sku - heights.sku
                        });
                        if (items.quantity.length === 0) {
                            items.select.css({
                                marginBottom: 58
                            });
                        }
                    } else {
                        if (items.quantity.length > 0) {
                            items.inner.css({
                                paddingBottom: sku - heights.sku + 25,
                                borderBottomWidth: 1
                            });
                        } else {
                            items.inner.css({
                                paddingBottom: sku - heights.sku + 25 + 51,
                                borderBottomWidth: 1
                            });
                            items.inner.css({
                                marginBottom: 7
                            });
                        }
                    }
                }
            }
        }

        function adjustSelectableItemListHeight() {
            var i, l = selectableItems.length;
            var w, cols = 0;
            var list = [];
            var item;
            if (l > 0) {
                w = selectableItems[0].item.parent().width();
                cols = w / 182 | 0;
                for (i = 0; i < l; ++i) {
                    item = selectableItems[i].item;
                    item.css({
                        clear: (i % cols) === 0 ? 'both' : ''
                    });
                    if ((i % cols) === 0) {
                        if (list.length > 0) {
                            adjustSelectableItemHeight(list);
                        }
                        list = [];
                    }
                    list.push(getItemHeights(item, true));
                }
                if (list.length > 0) {
                    adjustSelectableItemHeight(list);
                }
            }
        }
    });

</script>


