<div class="footer_inner_">
    <div class="pc2015-footer">
        <div class="pc2015-footer-1">
            <div class="clearfix">
                <div class="pc2015-left">
                    <div class="pc2015-footer-shop">
                        <h3><span>イオンリテールストア株式会社</span><br>イオン練馬店</h3>
                        <p>〒179-0072<br>東京都練馬区光が丘5-1-1<br>
                            販売責任者：店長 浅野裕之<br>
                            酒類販売管理者：近藤貴徳<br>
                            酒類販売管理研修の受講実施団体：日本チェーンストア協会<br>
                            受講日：平成27年10月6日</p>

                    </div>
                </div>
                <div class="pc2015-right">
                    <div class="pc2015-footer-shop">

                        <p>医薬品は下記店舗にて販売しています。</p>

                        <h3>イオンドラッグ練馬店</h3>
                        <p>店舗所在地：<br>東京都練馬区光が丘五丁目1番1号イオン練馬店1階<br>
                            許可番号：27練保所生薬き第205号<br>
                            許可年月日：平成28年3月1日～平成34年2月28日 【練馬区保健所長】</p>


                    </div>
                </div>
            </div>
            <div class="pc2015-footer-shop-list">
                <a href="/shop/area/shoplist.aspx">店舗一覧</a>
            </div>
        </div>

        <div class="pc2015-footer-2 clearfix">

            <div class="pc2015-left">
                <div class="pc2015-footer-delivery">
                    <h3 class="pc2015-designed">通常の配送料金</h3>
                    <div class="pc2015-area-other clearfix">   <h4>   ご注文金額  <strong>5,000円</strong>（税込）
                            以上で送料無料。</h4>   <p>4,999円（税込）以下の場合、配送料324円（税込）を頂戴いたします。</p>
                    </div>     <ul>     <p>  ※配送料はキャンペーンの実施により異なる場合があります。
                            <br>  ※予約品の送料は購入確認画面でご確認ください。<br>    ※  配送先エリアは  <a href="https://www.aeonnetshop.com/shop/deliveryarea/deliveryarea.aspx?shop=01050000805860" target="_blank"><b>こちら</b></a>をご確認ください。
                            <br>  ※1回のご注文可能金額は700円（税込）以上、15万円（税込）以下とさせていただきます。
                            <br>  ※代金引き換えでお支払いの場合、手数料108円（税込）を頂戴いたします。
                            <br>  ※天候・交通事情により配送できない場合があります。</p>  </ul>
                </div>
            </div>
            <div class="pc2015-right">
                <a href="/shop/netsuper/returntop.aspx?ismodesmartphone=on" class="pc2015-designed">スマートフォン版</a>
                <ul>
                    <li>●写真はイメージです。実際にお届けする商品とパッケージ等が異なる場合がございますので、あらかじめご了承ください。</li>
                    <li>●イオンのお店とインターネット販売では、商品の取扱に違いがある場合がございます。あらかじめご了承ください。</li>
                    <li>●メーカーの都合により、予告なく商品の規格、（パッケージ、容量など）原材料が変更になる場合がございます。ご購入後、パッケージなどで原材料をご確認ください。</li>
                    <li>●当サイトはプライバシー保護の為SSL暗号通信を採用しています。</li>
                </ul>
                <div class="pc2015-item-footer-pagetop">
                    <a href="#top" class="pc2015-designed pc2015-scroll" style="text-align: right;">画面上へ↑</a>
                </div>
            </div>
            <p>

            </p>
        </div>
        <div class="pc2015-footer-3 clearfix">
            <div class="pc2015-left">
                <dl>
                    <dt class="pc2015-designed">［お電話でのお問い合わせ］ センター（受付時間 9：00～21：00）</dt>
                    <dd class="pc2015-designed">0120-586-610</dd>
                </dl>
            </div>
            <div class="pc2015-right">
                <p>※携帯・PHSなどからもご利用いただけます。※午前9時～10時の間、お電話が集中し繋がりにくくなる場合がございます。ご不便をおかけして誠に恐れ入りますが、お電話が繋がりにくい場合は、午前10時以降にお電話をいただきますよう、お願い申し上げます。</p>
            </div>
        </div>

        <div class="pc2015-footer-4">
            <ul>
                <li class="pc2015-footer-nav-1"><a href="/shop/contact/contact.aspx" target="_blank">お問い合わせ</a></li>
                <li class="pc2015-separator">｜</li>
                <li class="pc2015-footer-nav-2"><a href="http://www.aeonsquare.net/privacy/" target="_blank">プライバシーポリシー</a></li>
                <li class="pc2015-separator">｜</li>

                <li class="pc2015-footer-nav-3"><a href="/shop/pages/01050000805860/00010000_goriyokiyaku.aspx" target="_blank">ご利用規約</a></li>
                <li class="pc2015-separator">｜</li>

                <li class="pc2015-footer-nav-4"><a href="/shop/contents1/00040000_waon_kiyaku.aspx" target="_blank">ネットWAON ポイント利用規約</a></li>
                <li class="pc2015-separator">｜</li>

                <li class="pc2015-footer-nav-5"><a href="/shop/CategoryShop/Legalinfo.aspx" target="_blank">特定商取引法に基づく表記</a></li>
                <li class="pc2015-separator">｜</li>
                <li class="pc2015-footer-nav-6"><a href="/shop/CategoryShop/Medicine.aspx" target="_blank">医薬品販売に関するご案内</a></li>
                <li class="pc2015-separator">｜</li>


                <li class="pc2015-footer-nav-7"><a href="/shop/pages/01050000805860/FAQ_top.aspx" target="_blank">よくあるご質問</a></li>

            </ul>
        </div>


    </div>



</div>


<div class="pc2015-footer-5">
    <p class="pc2015-copyright">Copyright (c) AEON Co., Ltd. All Rights Reserved.</p>
</div>