<a class="pc2015-designed pc2015-button-delivery" href="">配送時間・料金</a>

<a class="pc2015-designed pc2015-button-bookmark pc2015-disabled" href="">お買い物メモ</a>

<!--<a class="pc2015-designed pc2015-button-cart" title="レジに進む" href="javascript:void(0)" onclick="doGlobalCartShopSearch(); return false;">-->
<!--    <span id="global_totalprice"><span class="pc2015-button-cart-title-1">合計0点</span><span class="pc2015-button-cart-title-2">(税込)</span><span class="pc2015-button-cart-num">0円</span></span>-->
<!--</a>-->