<div class="pc2015-main-slider">

    <ul class="pc2015-main-slider-header pc2015-clearfix">
        <li><div id="main0" align="center"><a href="#">火曜市</a></div></li>

        <li><div id="main1" align="center"><a href="#">秋の味覚を楽しもう</a></div></li>

        <li><div id="main2" align="center"><a href="#">うれしい値・お値打ち</a></div></li>

        <li><div id="main3" align="center"><a href="#">まとめ買い予約</a></div></li>

        <li><div id="main4" align="center"><a href="#">クックパッド</a></div></li>
        
    </ul>
    <div class="pc2015-main-slider-body">
        <ul>


            <li><div id="list0"><a href="/shop/r/n01050000805860_r5001?linkid=nsmv_rAyoqFGe"><img src="/img/banner/7568.jpg" alt="火曜市" width="766" height="199"></a></div></li>




            <li><div id="list1"><a href="/shop/r/n01050000805860_r500P?linkid=nsmv_ednwUPTQ"><img src="/img/banner/12732.jpg" alt="秋の味覚を楽しもう" width="766" height="199"></a></div></li>




            <li><div id="list2"><a href="/shop/r/n01050000805860_r502J23?linkid=nsmv_fgoP6TgA"><img src="/img/banner/12494.jpg" alt="うれしい値・お値打ち" width="766" height="199"></a></div></li>




            <li><div id="list3"><a href="/shop/r/n01050000805860_r0916?linkid=nsmv_SBBJYonG"><img src="/img/banner/8502.jpg" alt="まとめ買い予約" width="766" height="199"></a></div></li>




            <li><div id="list4"><a href="/shop/r/n01050000805860_r60?linkid=nsmv_EZuU6Lxt"><img src="/img/banner/12653.jpg" alt="クックパッド" width="766" height="199"></a></div></li>

            
        </ul>
    </div>
</div>

<scrip src="js/jquery.jcarousel.min.js"></scrip>
<scrip src="js/shop.js"></scrip>