<div class="pc2015-main-ads">

    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-1-1" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/9734.jpg'); ?>">
    </a>

    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-2-1" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/7509.jpg'); ?>">
    </a>


    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-1-2" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/12157.jpg'); ?>">
    </a>


    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-2-2" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/7366.jpg'); ?>">
    </a>


<!--    <div style="left:585px;position: absolute;">-->
<!--        <a href="tokyo.nerima" target="_blank">-->
<!--            <img src="tokyo.nerima" border="0">-->
<!--        </a>-->
<!--    </div>-->

</div>