<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

//    $image = 'new_products_content_widget_grid';
    $image = 'bundled_product_list_anhht'; //view.xml
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();


    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="pc2015-main-block block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">

<!--        Phan header cua block => in ra title trong admin-->
        <div class="pc2015-main-block-header">
            <h2><?php echo ($title) ? $title : '【トップバリュ 感謝の値下げ】'; ?></h2>
            <a href="#" class="pc2015-main-block-more pc2015-for-member">一覧を見る</a>
            <a href="#" class="pc2015-main-block-toggle pc2015-designed">＋</a>
        </div>
<!--        End phan header block -->

        <div class="block-content pc2015-main-block-body pc2015-item-carousel">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class=" products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="pc2015-item-list product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
<!--                        --><?php //var_dump($_item->getId());die;?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item pc2015-item">' : '</li><li class="product-item pc2015-item">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name pc2015-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link pc2015-item-name-title">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>


<!--                                //-------------------------------------------->
<!--                                <div class="product-options-wrapper" id="product-options-wrapper" data-hasrequired="* Verplichte velden">-->
<!--                                    --><?php //if($_item->getTypeId() === 'configurable') : ?>
<!--                                        --><?php //foreach($_item->getTypeInstance()->getConfigurableAttributes($_item) as $attribute) : ?>
<!--                                            <div class="field">-->
<!--                                                <label class="label" for="select_--><?php //echo $attribute->getAttributeId(); ?><!--"><span>--><?php //echo $attribute->getLabel() ?><!--</span></label>-->
<!--                                                --><?php //$values = $attribute->getOptions(); ?>
<!--                                                <div class="control">-->
<!--                                                    <select id="select_--><?php //echo $attribute->getAttributeId() ?><!--" rel="--><?php //echo $attribute->getAttributeId()?><!--" name="options[--><?php //echo $attribute->getAttributeId() ?><!--]" class="product-option product-custom-option---><?php //echo $attribute->getAttributeId() ?><!-- admin__control-select" data-selector="options[--><?php //echo $attribute->getAttributeId() ?><!--]">-->
<!--                                                        --><?php //foreach($values as $value): ?>
<!--                                                            <option value="--><?php //echo $value['value_index'] ?><!--">--><?php //echo  $value['label'] ?><!--</option>-->
<!--                                                        --><?php //endforeach; ?>
<!--                                                    </select>-->
<!--                                                </div>-->
<!--                                            </div>-->
<!--                                        --><?php //endforeach; ?>
<!--                                    --><?php //endif; ?>
<!--                                    <label class="label"><span>Quantity</span></label>-->
<!--                                    <div class="field">-->
<!--                                        <div class="control">-->
<!--                                            <input type="number" class="qty-select" value="1">-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                    <br>-->
<!--                                </div>-->
<!--                                -->
<!--                                //---------------------------------------------------->


                               
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

<!--                                Soluong-->
                                <dl class="pc2015-item-quantity">
                                    <dt>数量</dt>
                                    <dd class="pc2015-cart-quantity" id="010500008058604902121230624_qty" name="010500008058604902121230624_qty">1</dd>
                                </dl>
                                <a href="#" class="pc2015-designed pc2015-cart-inc">+</a>
                                <a href="#" class="pc2015-designed pc2015-cart-dec">-</a>
                            <!--End so luong-->
                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary pc2015-item-cart"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary pc2015-item-cart"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showWishlist || $showCompare): ?>
<!--                                            <div class="actions-secondary" data-role="add-to-links">-->
<!--                                                --><?php //if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
<!--                                                    <a href="#"-->
<!--                                                       data-post='--><?php ///* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?><!--'-->
<!--                                                       class="action towishlist" data-action="add-to-wishlist"-->
<!--                                                       title="--><?php ///* @escapeNotVerified */ echo __('Add to Wish List') ?><!--">-->
<!--                                                        <span>--><?php ///* @escapeNotVerified */ echo __('Add to Wish List') ?><!--</span>-->
<!--                                                    </a>-->
<!--                                                --><?php //endif; ?>
<!--                                                --><?php //if ($block->getAddToCompareUrl() && $showCompare): ?>
<!--                                                    --><?php //$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
<!--                                                    <a href="#" class="action tocompare"-->
<!--                                                       data-post='--><?php ///* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?><!--'-->
<!--                                                       title="--><?php ///* @escapeNotVerified */ echo __('Add to Compare') ?><!--">-->
<!--                                                        <span>--><?php ///* @escapeNotVerified */ echo __('Add to Compare') ?><!--</span>-->
<!--                                                    </a>-->
<!--                                                --><?php //endif; ?>
<!--                                            </div>-->
                                        <?php endif; ?>

                                        <a href="javascript:void(0);" class="pc2015-for-member pc2015-designed pc2015-item-memo pc2015-disabled">お買物メモに登録</a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>


