<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

namespace Cowell\Aeon\Block;

use Magento\Framework\DataObject\IdentityInterface;
use Magento\Framework\UrlInterface;
use Magento\Framework\View\Element\Template;
use Magento\Widget\Block\BlockInterface;

/**
 * Catalog Products List widget block
 * Class ProductsList
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class HeaderTop extends Template implements BlockInterface
{
 protected function _beforeToHtml()
 {
//     $scope = $this->_scopeConfig;
//     $phone = $scope->getValue('general/store_information/phone');
//     $this->setData('phone',$phone);
//
//     $mail = $scope->getValue('trans_email/ident_general/mail');
//     $this->setData('mail',$mail);
//
//     $mail = $scope->getValue('social/social_config/facebook');
//     $this->setData('facebook',$mail);

     return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
 }
}
