<?php
$banners = $this->getData('banners');
$auto = $this->getData('auto') ? "true" : "false";
$pager = $this->getData('pager') ? "true" : "false";
$speed = intval($this->getData('speed'));
$bannerSlide = $this->getData('slide');
$mediaURL = $this->getData('mediaURL');
?>

<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Dmit_Banner::css/jquery.bxslider.css') ?>"/>
<ul class="bxslider">
    <?php foreach ($banners as $banner) { ?>
        <li>
            <a href="<?php echo $banner['link'] ?>">
                <img src="<?php echo $mediaURL . $banner['image']; ?>"/>
            </a>
        </li>
    <?php } ?>
</ul>

<script>
    require(['jquery', 'bxslider'], function ($) {
        $(function () {
            $('.bxslider').bxSlider({
                auto: <?php echo $auto ?>,
                pager: <?php echo $pager ?>,
                speed: <?php echo $speed ?>
            });
        });
    });
</script>

