<?php
$banners = $this->getData('banners');
$auto = $this->getData('auto') ? "true" : "false";
$pager = $this->getData('pager') ? "true" : "false";
$speed = intval($this->getData('speed'));
$bannerSlide = $this->getData('slide');
$mediaURL = $this->getData('mediaURL');
?>

<?php if ($bannerSlide == 'bxslider') { ?>
    <link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Dmit_Banner::css/jquery.bxslider.css') ?>"/>
    <ul class="bxslider">
        <?php foreach ($banners as $banner) { ?>
            <li>
                <a href="<?php echo $banner['link'] ?>">
                    <img src="<?php echo $mediaURL . $banner['image']; ?>"/>
                </a>
            </li>
        <?php } ?>
    </ul>

    <script>
        require(['jquery', 'bxslider'], function ($) {
            $(function () {
                $('.bxslider').bxSlider({
                    auto: <?php echo $auto ?>,
                    pager: <?php echo $pager ?>,
                    speed: <?php echo $speed ?>
                });
            });
        });
    </script>
<?php } else if ($bannerSlide == 'flexslider') {  ?>

    <link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Dmit_Banner::css/flexslider.css') ?>"/>
    <div class="flexslider">
        <ul class="slides">
            <?php foreach ($banners as $banner) { ?>
                <li>
                    <a href="<?php echo $banner['link'] ?>">
                        <img src="<?php echo $mediaURL . $banner['image']; ?>"/>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </div>


    <script>
        require(['jquery', 'flexslider'], function ($) {
            $(function () {
                $('.flexslider').flexslider({
                    animation: "slide"
                });
            });
        });
    </script>
<?php }?>

