<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 8/21/2017
 * Time: 1:29 PM
 */

namespace Cowll\EShopper\Block;

use Magento\Framework\View\Element\Template;
class LogoRight extends Template
{
    protected function _beforeToHtml()
    {
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}