<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __(''); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart fix-format-card">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty fix-padding">

                    <div class="control control-product">
                        <label class="label" for="qty"><span class="fomart-qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                        <input type="number"
                                       name="qty"
                                       id="number"
                                       class="format-num-card"
                                       maxlength="12"
                                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="info-text qty"
                                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                    <button type="button" onclick="incrementValue()" spinner-button="up" title="add 1" class="fixbntc">+</button>
                    <button type="button" onclick="decrementValue()" spinner-button="down" title="subtract 1" class="fixbntt">-</button>
                </div>
            <?php endif; ?>
            <div class="actions fix-1">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart formart-button"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
            <div class="format-mages-card"></div>

        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
    <script type="text/javascript">
        function incrementValue()
        {
            var value = parseInt(document.getElementById('number').value, 10);
            value = isNaN(value) ? 0 : value;
            if(value<10){
                value++;
                document.getElementById('number').value = value;
            }
        }
        function decrementValue()
        {
            var value = parseInt(document.getElementById('number').value, 10);
            value = isNaN(value) ? 0 : value;
            if(value>1){
                value--;
                document.getElementById('number').value = value;
            }

        }
    </script>
<?php endif; ?>
<div class="adress-product">
    <p class="fomart-1">お届けについて</p>

    <li><b>配送区分：</b> 在庫品</li>
    <li><b>支払方法：</b> イオンカード、他社カード、代引き(店舗によって商品券での支払い含む)、玄関先WAON
        広域エリアでは玄関先WAONがご利用できません</li>
    支払方法：
</div>