<h1>Du bao thoi tiet phtml</h1>

<div id="datepicker"></div>
<h3>Thời tiết 5 ngày tới</h3>
<div style="background-color: red">
<div id="weather"></div>
</div>
<script>
    require(['jquery','simple_weather','mage/calendar'],function($)
    {

        // Docs at http://simpleweatherjs.com
        $(document).ready(function() {
            $.simpleWeather({
                woeid: '2357536', //2357536
                location: 'Ha Noi',
                unit: 'c',
                success: function(weather) {
                    html = '<h2>'+weather.temp+'&deg;'+weather.units.temp+'</h2>';
                    html += '<ul><li>'+weather.city+', '+weather.region+'</li>';
                    html += '<li class="currently">'+weather.currently+'</li>';
                    html += '<li>'+weather.alt.temp+'&deg;C</li></ul>';

                    for(var i=0;i<weather.forecast.length;i++) {
                        html += '<p>'+weather.forecast[i].day+': '+weather.forecast[i].high+'</p>';
                    }

                    $("#weather").html(html);
                },
                error: function(error) {
                    $("#weather").html('<p>'+error+'</p>');
                }
            });
        });
        $("#datepicker").datepicker();
    });

</script>