<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Link */
?>
<div class="pc2015-lower">
    <dl>
        <dt>注目ワード</dt>
        <dd>
            <ul>
                <a href="/shop/goods/csearch.aspx?keyword=新商品&amp;shop=01050000805860" class="pc2015-for-member"><li>新商品</li></a>
                <a href="/shop/goods/csearch.aspx?keyword=アイス&amp;shop=01050000805860" class="pc2015-for-member"><li>アイス</li></a>
                <a href="/shop/goods/csearch.aspx?keyword=新学期準備&amp;shop=01050000805860" class="pc2015-for-member"><li>新学期準備</li></a>
                <a href="/shop/goods/csearch.aspx?keyword=低糖質&amp;shop=01050000805860" class="pc2015-for-member"><li>低糖質</li></a>
                <a href="/shop/goods/csearch.aspx?keyword=やさしごはん&amp;shop=01050000805860" class="pc2015-for-member"><li>やさしごはん</li></a>
            </ul>
        </dd>
    </dl>
</div>