<?php
/**
 * Created by PhpStorm.
 * User: nguyenduyhung
 * Date: 8/22/17
 * Time: 10:01 AM
 */

namespace Cowell\Delivery\Block;


class  DeliveryInformation extends \Magento\Framework\View\Element\Template {

  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    protected function _beforeToHtml()
    {   
        $arrStatus[] = null;
        $dataList = ["08:30","11:30"];
        $deadline = '08:30';
        
        $monthCurrent = date('m');
        $dayCurrent = date('d');
        $nextDay =  date('d') + 1;
        
        $nextMonth = date('m');
        
        // If today is last of month
        if ($dayCurrent === date('d',strtotime(date('Y-m-t')))) {
            $nextDay = '01';
            $nextMonth = date('m') + 1;
        }
        
//        $statusDelivery = getStatusOfDelivery($deadline);
//        $statusDeliveryNext = getStatusOfDelivery($nextDate);
        
        
        foreach ($dataList as $value) {
            $deadline = $value;
            $nextDate = date('Y-m-d',strtotime("+1 day")) . ' ' .$deadline ; 
            $statusDelivery = $this->getStatusOfDelivery($deadline);
            $statusDeliveryNext =  $this->getStatusOfDelivery($nextDate);
           
            $arrStatusItem[] = null;
            $arrStatusItem['delivery_time'] = '12:00～14:00';
            $arrStatusItem['deadline'] = $deadline;
            $arrStatusItem['status_delivery'] = $statusDelivery;
            $arrStatusItem['status_delivery_next'] = $statusDeliveryNext;
           
            array_push($arrStatus, $arrStatusItem);

            
        } 
        
        $arrStatus = array_filter($arrStatus);
        
        // Set param to use in deliveryinfo.phtml                        
        $this->setData('month_current',$monthCurrent);
        $this->setData('day_current',$dayCurrent);
        $this->setData('last_day',$nextDay);
        $this->setData('last_month',$nextMonth);
        $this->setData('arr_status',$arrStatus);
//        $this->setData('status_delivery',$statusDelivery);
//        $this->setData('status_delivery_next',$statusDeliveryNext);
   
        
    }
    
    public function getStatusOfDelivery ($deadline) {
        
        $statusDelivery = '○';
        
        if (!isset($deadline)) {
            if (strtotime(date('H:i')) > strtotime($deadline)) {
                // do something
                $statusDelivery = 'x'; 
            } 
        }

        return $statusDelivery;
    }
    
}
