<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Magefan\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post-view">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-header clearfix"></div>

        <h3 class="common_headline1_"><?php echo $_post->getTitle(); ?></h3>

        <div class="post-content">
            <div class="post-description clearfix">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </div>
                <?php } ?>
                <div class="post-text-hld">
                    <h3 class="news-title"><?php echo $_post->getTitle(); ?></h3>
                    <?php echo $block->getContent(); ?>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    h3.news-title {
        font-size: 18px;
        font-weight: bold;
        color: #000000;
        margin-bottom: 15px;
        padding: 0 0 10px 0;
        border-bottom: 1px solid #e0e0e0;
    }

    .common_headline1_ {
        margin: 0 0 20px 0;
        padding: 6px 10px;
        color: #333333;
        font-size: 21px;
        font-weight: normal;
        line-height: 1.4;
        border-bottom: 1px solid #999999;
        border-left: 7px solid #b0237b;
    }
</style>
