<div class="container fix-full-width">
    <div class="pc2015-main-block pc2015-detail-category">
        <div class="pc2015-main-block-header">
            <h2>関連カテゴリ</h2>
            <a href="#" class="pc2015-main-block-toggle pc2015-designed">＋</a>
        </div>
        <div class="pc2015-main-block-body" >
            <ul>
                <a href="#">おすすめ・特集・トップバリュ</a>
                ＞ <a href="#">【トップバリュ】</a>
                <br><a href="#">おすすめ・特集・トップバリュ</a>
                ＞ <a href="#">【トップバリュ】</a>
                ＞ <a href="#">牛乳・乳製品</a>
                <br><a href="#">おすすめ・特集・トップバリュ</a>
                ＞ <a href="#">【おすすめトップバリュ商品】</a>
                <br><a href="#">おすすめ・特集・トップバリュ</a>
                ＞ <a href="#">【おすすめトップバリュ商品】</a>
                ＞ <a href="#">【食品】</a>
                <br><a href="#">食品</a>
                ＞ <a href="#">牛乳・乳製品・たまご</a>
                <br><a href="#">食品</a>
                ＞ <a href="#">牛乳・乳製品・たまご</a>
                ＞ <a href="#">ヨーグルト</a>
                <br>
            </ul>
        </div>
    </div>
</div>