<?php
namespace Robin\LuyenLayout\Block;

class block1 extends \Magento\Framework\View\Element\Template{
    public function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}