<div class="pc2015-main-info" id="info">
    <h2>お知らせ</h2>
    <dl>
        <dt>2017年08月17日</dt>
        <dd>



            <a href="/shop/t/t6336/" target="_blank">


                相模屋食料（株）国産大豆絹3個パック・北海道産大豆絹3個パック 撤去・回収・返品の件
            </a>

            <img src="<?php echo $block->getViewFileUrl('images/usr/icon/icon_new2.png'); ?>">
        </dd>

        <dt>2017年08月17日</dt>
        <dd>



            <a href="/shop/t/t6319/" target="_blank">


                ご不在時の再配達サービスについて
            </a>

            <img src="<?php echo $block->getViewFileUrl('images/usr/icon/icon_new2.png'); ?>">
        </dd>

        <dt>2017年08月16日</dt>
        <dd>



            <a href="/shop/t/t6331/" target="_blank">


                2018年【戌年】喪中・年賀ハガキ印刷をご注文のお客さまへ
            </a>

            <img src="<?php echo $block->getViewFileUrl('images/usr/icon/icon_new2.png'); ?>">
        </dd>

        <dt>2017年04月14日</dt>
        <dd>



            <a href="/shop/t/t5698/" target="_blank">


                商品のご注文について
            </a>


        </dd>


    </dl>

</div>