<div class="pc2015-main-ads">

    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-1-1" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/9734.jpg'); ?>">
    </a>

    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-2-1" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/7509.jpg'); ?>">
    </a>


    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-1-2" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/12157.jpg'); ?>">
    </a>


    <a href="#" class="pc2015-ad pc2015-for-member pc2015-ad-279x99 pc2015-ad-pos-2-2" target="_blank">
        <img width="279" height="99" alt="" src="<?php echo $block->getViewFileUrl('images/banner/7366.jpg'); ?>">
    </a>


    <div style="left:565px;position: absolute;width: 100%">
        <!-- PLACEHOLDERtag start-->
       <div id="CM8_FORMAT_rectangle_banner" style="display:none"></div>
        <span id="CM8CSE_3E4F7825676D">
            <span id="CM8BWE_3E4F7825676D">
                <div>
                    <a href="#" target="_blank">
                    <img src="https://web-jp.ad-v.jp/data/1840161/cola_banner200_170518.jpg" border="0">
                    </a>
                </div>
            </span><!-- CM8BWE_3E4F7825676D -->
        </span><!-- CM8CSE_3E4F7825676D -->
        <!-- PLACEHOLDERtag end-->
    </div>

</div>