<div class="pc2015-side-banner-upper">
    <a href="#" class="pc2015-banner pc2015-banner-200x200"><img src="https://www.aeonnetshop.com/pc2015/img/shop/banner/200x200-0001.jpg" alt="おうちでイオン イオンドラッグ 医薬品をおうちへお届け！ 入会金 年会費 無料 ネットでらくらくご注文、ご自宅までお届けします。" width="200" height="200"></a>
    <a href="#" class="pc2015-banner pc2015-banner-200x200"><img src="https://www.aeonnetshop.com/pc2015/img/shop/banner/200x200-0004.jpg" alt="おうちでイオン　イオンショップ" width="200" height="200"></a>
</div>