<div class="pc2015-side-delivery">
    <div>
        <a href="" class="pc2015-designed pc2015-side-delivery-reload">最新の配送状況を確認</a>
        <div id="deliver_area">


            <div class="pc2015-timetable">
                <table border="0" cellpadding="0" cellspacing="0">
                    <caption><strong>地域内全域</strong></caption>


                    <thead>
                    <tr>

                        <th>配送<br>日時</th>

                        <th>締切<br>時間</th>

                        <th class="pc2015-highlight" align="justify">08月<br>29日</th>

                        <th class="pc2015-highlight" align="justify">08月<br>30日</th>

                    </tr>
                    </thead>
                    <tbody>

                    <tr class="pc2015-timetable-row-1">
                        <td class="border">12:00～14:00</td>
                        <td class="deadlineTime">～09:00</td>

                        <td>×</td>



                        <td class="pc2015-timetable-2">○</td>



                    </tr>
                    <tr class="pc2015-timetable-row-2">
                        <td colspan="4">






                            <p class="pc2015-time-2">締切時間の目安<br><span>あと<strong>28時間43分</strong></span></p>




                        </td>
                    </tr>



                    <tr class="pc2015-timetable-row-1">
                        <td class="border">14:00～16:00</td>
                        <td class="deadlineTime">～11:00</td>


                        <td class="pc2015-timetable-1">○</td>




                        <td class="pc2015-timetable-2">○</td>



                    </tr>
                    <tr class="pc2015-timetable-row-2">
                        <td colspan="4">


                            <p class="pc2015-time-1">締切時間の目安<br><span>あと<strong>06時間43分</strong></span></p>





                            <p class="pc2015-time-2">締切時間の目安<br><span>あと<strong>30時間43分</strong></span></p>




                        </td>
                    </tr>



                    <tr class="pc2015-timetable-row-1">
                        <td class="border">16:00～18:00</td>
                        <td class="deadlineTime">～13:00</td>


                        <td class="pc2015-timetable-1">○</td>




                        <td class="pc2015-timetable-2">○</td>



                    </tr>
                    <tr class="pc2015-timetable-row-2">
                        <td colspan="4">


                            <p class="pc2015-time-1">締切時間の目安<br><span>あと<strong>08時間43分</strong></span></p>





                            <p class="pc2015-time-2">締切時間の目安<br><span>あと<strong>32時間43分</strong></span></p>




                        </td>
                    </tr>



                    <tr class="pc2015-timetable-row-1">
                        <td class="border">18:00～20:00</td>
                        <td class="deadlineTime">～15:00</td>


                        <td class="pc2015-timetable-1 pc2015-timetable-caution">△</td>




                        <td class="pc2015-timetable-2">○</td>



                    </tr>
                    <tr class="pc2015-timetable-row-2">
                        <td colspan="4">


                            <p class="pc2015-time-1">締切時間の目安<br><span>あと<strong>10時間43分</strong></span></p>





                            <p class="pc2015-time-2">締切時間の目安<br><span>あと<strong>34時間43分</strong></span></p>




                        </td>
                    </tr>



                    <tr class="pc2015-timetable-row-1">
                        <td class="border">19:00～21:00</td>
                        <td class="deadlineTime">～15:00</td>

                        <td>×</td>



                        <td class="pc2015-timetable-2">○</td>



                    </tr>
                    <tr class="pc2015-timetable-row-2">
                        <td colspan="4">






                            <p class="pc2015-time-2">締切時間の目安<br><span>あと<strong>34時間43分</strong></span></p>




                        </td>
                    </tr>




                    </tbody>
                </table>
            </div>


        </div>
    </div>
</div>