<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Cowell_Delivery::css/bootstrap.min.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Cowell_Delivery::css/delivery.css') ?>"/>


<div class="pc2015-overlay" style="opacity: 0.2; display: block;"></div>

<a class="delivery button pc2015-designed pc2015-button-delivery" id="deliveryBtn">配送時間・料金</a>

<!-- <button id="deliveryBtn" class="delivery button pc2015-designed pc2015-button-delivery">配送時間・料金</button> -->


               <!--  <div class="modal-header">
                </div> -->
               <div class="pc2015-delivery-menu" style="display:none;">
                   <div>
                        <a href="javascript:void(0)" onclick="doCategoryDeriverSearch(); return false;" class="pc2015-designed">最新の配送状況を確認</a>

                        <div >
                            <div id="globaldeliver_area">
                                <div class="pc2015-timetable">
                                    <table border="0" cellpadding="0" cellspacing="0">
                                        <caption><strong>地域内全域</strong></caption>
                                        <thead>
                                        <tr>
                                            <th>配送<br>日時</th>
                                            <th>締切<br>時間</th>
                                            <th class="pc2015-highlight" align="justify"><?php echo $this->getData('month_current'); ?>月<br><?php echo $this->getData('day_current'); ?>日</th>
                                            <th class="pc2015-highlight" align="justify"><?php echo $this->getData('last_month'); ?>月<br><?php echo $this->getData('last_day'); ?>日</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php $data = $this->getData('arr_status');
                                                foreach ($data as $dataItem) {
                                             ?>
                                        <tr class="pc2015-timetable-row-1">
                                            <td class="border">12:00～14:00</td>
                                            <td class="deadlineTime">～<?php echo $dataItem['deadline']; ?></td>
                                            <td><?php
                                                        echo $dataItem['status_delivery'];
                                                    ?></td>
                                            <td class="pc2015-timetable-2"> <?php
                                                        echo $dataItem['status_delivery_next'];
                                                    ?></td>
                                        </tr>
                                         <?php

                                                }

                                            ?>
                                        <tr class="pc2015-timetable-row-2 pc2015-timetable-on-4" style="display: none;">
                                            <td colspan="4">
                                                <p class="pc2015-time-2">締切時間の目安<br><span>あと<strong>19時間27分</strong></span></p>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                   </div>
               </div>
                <!-- <div class="modal-footer">
                    
                </div> -->

<script>
    require(['jquery','delivery'], function ($) {
        $(window).ready(function() {
            var $win = $(window);
            var $overlay = $('.pc2015-overlay').bind('click', function() {
                  hideAllPopups();
                  return false;
                });

            var popups = {};
                makePopup('delivery', '.pc2015-delivery-menu', {
                      heightOffset: 240,
                      minHeight: 160
                    });

            $('.pc2015-button-delivery').bind('click', function() {
              showPopup('delivery');
              return false;
            });

            function makePopup(name, selector, options) {
                var p = {
                  name: name,
                  popup: $(selector),
                  overlay: 0.2,
                  heightOffset: null,
                  minHeight: null,
                  autohide: !true,
                  global: false,
                  visible: false
                };
                $.extend(p, options);
                if (p.button) {
                  p.button.bind('click', function() {
                    showPopup(name);
                    return false;
                  });
                }
                if (p.autohide) {
                  p.popup.bind('mouseleave', function() {
                    hidePopup(name);
                    hideOverlay();
                  });
                }
                if (!$.isFunction(p.after)) {
                  p.after = $.noop;
                }
                return (popups[name] = p);
              }


            function showPopup(name) {
                console.log('wwwww: '+ name);
                var x, popup;
                for (x in popups) {
                  if (x === name) {
                    popup = popups[x];
                  } else {
                    hidePopup(x);
                  }
                }
                //hideMenu(1);
                if (!popup) return;
                if (popup.visible) {
                  hideOverlay();
                  if (popup.button) {
                    popup.button.removeClass('pc2015-active');
                  }
                  popup.popup.stop(true, true).fadeOut('fast');
                } else {
                  if(name != 'memo') {
                    showOverlay(popup.overlay, popup.global);
                  }
                  if (popup.button) {
                    popup.button.addClass('pc2015-active');
                  }
                  popup.popup.stop(true, true);
                  setPopupHeight(popup);
                  popup.popup.fadeIn('fast');
                }
                popup.visible = !popup.visible;
                popup.after(popup);
              }

              function hidePopup(name) {
                var popup = popups[name];
                if (popup) {
                  popup.popup.stop(true, true).hide();
                  popup.visible = false;
                  if (popup.button) {
                    popup.button.removeClass('pc2015-active');
                  }
                  popup.after(popup);
                  return true;
                }
                return false;
              }

              function hideAllPopups() {
                var name;
                var result1 = hideMenu(1);
                var result2 = false;
                for (name in popups) {
                  result2 = hidePopup(name) || result2;
                }
                hideOverlay();
                return result1 || result2;
              }

            

              function showOverlay(opacity, global) {
                $overlay.css({
                  opacity: isFinite(opacity) ? opacity : 0.2
                }).toggleClass('pc2015-global-overlay', global).show();
              }

              function hideOverlay() {
                $overlay.hide();
              }

            function setPopupHeight(popup) {
               if(popup.popup.html() == null){
                if(popup.popup.html().match("買い物かごには商品が入っておりません")){return false;}
               }
              
                if (popup.heightOffset !== null) {
                  var h = $win.height() - popup.heightOffset;
                  if (popup.minHeight !== null && h < popup.minHeight) {
                    h = popup.minHeight;
                  }
                  popup.popup.height(h);
                  if (popup.name === 'cart' || popup.name === 'delivery') {
                    popup.popup.find('>div').height(h);
                  }
                }
              }


            $('#delivery_menu_top').modal('hide');

            // $('#deliveryBtn').on('click', function () {
            //     $('#delivery_menu_top').modal('show');
            // });
           
        });

    })

</script>