<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
</div>
<div class="mainmenu pull-left">
    <ul class="nav navbar-nav collapse navbar-collapse">
        <li><a href="/" class="active">Home</a></li>
        <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li><a href="<?php echo $this->getUrl('products') ?>">Products</a></li>
                <li><a href="<?php echo $this->getUrl('checkout', ['_secure' => true]);?>"><i class="fa fa-crosshairs"></i> Checkout</a></li>
                <li><a href="<?php echo $this->getUrl('checkout/cart', ['_secure' => true]);?>"><i class="fa fa-shopping-cart"></i> Cart</a></li>
                <li><a href="<?php echo $this->getUrl('customer/account/login') ?>"><i class="fa fa-lock"></i> Login</a></li>
            </ul>
        </li>
        <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li><a href="#">Blog List</a></li>
                <li><a href="#">Blog Single</a></li>
            </ul>
        </li>
        <li><a href="#">404</a></li>
        <li><a href="<?php echo $this->getUrl('contact') ?>">Contact</a></li>
    </ul>
</div>