<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
        USA
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a href="#">Canada</a></li>
        <li><a href="#">UK</a></li>
    </ul>
</div>

<div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
        DOLLAR
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <li><a href="#">Canadian Dollar</a></li>
        <li><a href="#">Pound</a></li>
    </ul>
</div>