
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/shop.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/common.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/reset.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/etc.css') ?>"/>

<?php

/**
 * Template for displaying products list widget
 *
 * @var $block \Cowell\Productlist\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
//    $image = 'bundled_product_list_anhht'; //view.xml
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="pc2015-main-block">
        <!--        start header block -->
        <div class="pc2015-main-block-header">
            <h2><?php echo ($title) ? $title : '【トップバリュ 感謝の値下げ】'; ?></h2>
            <a href="#" class="pc2015-main-block-more pc2015-for-member">一覧を見る</a>
            <a href="#" class="pc2015-main-block-toggle pc2015-designed">＋</a>
        </div>
        <!--        End header block -->

        <div class="pc2015-main-block-body pc2015-item-carousel jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;width: 1200px;">
            <div class="jcarousel-clip jcarousel-clip-horizontal" style="position: relative;" >
            <?php /* @escapeNotVerified */
            echo '<!-- ' . $image . '-->' ?>
            
                <ul class="pc2015-item-list jcarousel-list jcarousel-list-horizontal <?php /* @escapeNotVerified */
                echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */
                        echo ($iterator++ == 1) ? '<li class="pc2015-item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">' : '</li><li class="pc2015-item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">' ?>
                        <!--<div class="product-item-info">-->
                            <a href="<?php /* @escapeNotVerified */
                            echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <!--<div class="product-item-details">-->
                                <strong class="product-item-name pc2015-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */
                                       echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link pc2015-item-name-title">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>
                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                <div class="product-add-form">
                                     <!--start form them, bot so luong san pham vao gio hang-->
                                <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_item) ?>" method="post" id="product_addtocart_form">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                    <input type="hidden" name="selected_configurable_option" value="" />
                                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                                    <input type="hidden" name="qty" id="qty-<?php echo $_item->getId()?>" maxlength="12" value="1" title="Qty" class="input-text">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    
                                    <!--<div class="product-item-actions">-->
                                        <?php if ($showCart): ?>
                                            <!--<div class="actions-primary">-->
                                                <?php if ($_item->isSaleable()): ?>
                                                    <!-- start so luong san pham-->
                                                    <!--<div class="control">-->
                                                        <dl class="pc2015-item-quantity">
                                                            <dt>数量</dt>
                                                                <dd class="pc2015-cart-quantity"
                                                                        id="<?php echo $_item->getId(); ?>"
                                                                        name="<?php echo $_item->getName(); ?>" value="" >1
                                                                </dd>
                                                        </dl>
                                                    <!--</div>-->
                                                    <a href="javascript:void(0)" class="pc2015-designed pc2015-cart-inc">+</a>
                                                    <a href="javascript:void(0)" class="pc2015-designed pc2015-cart-dec">-</a>
                                                    <!--end so luong san pham-->
                                                    <div class="action">
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary pc2015-item-cart "
                                                                    id="product-addtocart-button"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                                    echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="submit" title="<?php /* @escapeNotVerified */
                                                            echo __('カートに入れる') ?>">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('カートに入れる') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            
                                                            <button type="submit" class="action tocart primary pc2015-item-cart">

                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('カートに入れる hhh') ?></span>
                                                            </button>

                                                        <?php endif; ?>

                                                    </div>
                                                    
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                    <!--neu san pham con hang thi-->
                                                        <div class="stock available">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                    <!--neu san pham het hang-->
                                                        <div class="stock unavailable">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <!--</div>-->
                                        <?php endif; ?>
                                </form>
                                <!--end form them, bot so luong san pham vao gio hang-->

                                    <!--</div>-->
                                        <a href="javascript:void(0);" class="pc2015-for-member pc2015-designed pc2015-item-memo pc2015-disabled">お買物メモに登録</a>
                                    </div>
                                <?php endif; ?>
                            <!--</div>-->
                        <!--</div>-->
                        <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ul>
                
            </div>
            
            <?php echo $block->getPagerHtml() ?>
            <!--preview button-->
                <div class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal" disabled="false" style=""></div>
                <!--next button-->
                <div class="jcarousel-next jcarousel-next-horizontal" disabled="false" style="display: block;"></div>   
        </div>
    </div>
<?php endif; ?>

<script>
    require(['jquery','jcarousel'], function ($) {
        $(function () {
            var noMember = $('body').hasClass('pc2015-no-member');
            $('.pc2015-item,.pc2015-cart-item').each(function () {
                setupCartItem($(this), noMember);
            });

            $('.pc2015-main-block').each(function () {
                setupMainBlock($(this));
            });
            $('.pc2015-item-carousel').each(function() {
                setupItemCarousel($(this));
              });
              
              function setupItemCarousel(jq) {
                var items = jq.find('.pc2015-item');
                var itemCarousel = {
                  itemCarousel: jq,
                  count: items.length
                };
                var heightsList = [];
                if (jq.hasClass('pc2015-item-list-selectable')) {
                  items.each(function(i) {
                    heightsList.push(getItemHeights($(this), true));
                  });
                  adjustSelectableItemHeight(heightsList);
                } else {
                  items.each(function(i) {
                    heightsList.push(getItemHeights($(this)));
                  });
                  adjustItemHeight(heightsList);
                }
                itemCarousel.itemCarousel.jcarousel({
                  scroll: 1,
                  setupCallback: function(jc) {
                    jc.buttonNext.bind('click', function() {
                      return false;
                    });
                    jc.buttonPrev.bind('click', function() {
                      return false;
                    });
                  }
                });
                // chua xu ly duoc khi man hinh co lai thi moi hien button next
//                pc2015.$win.bind('resize', $.debounce(500, function() {
//                    adjustItemCarousel(itemCarousel);
//                  }));
                  adjustItemCarousel(itemCarousel);

              }
              function adjustItemCarousel(itemCarousel) {
                var w0 = itemCarousel.itemCarousel.parent().width();
                var w = 717;
                var max = 4;
                var jc = itemCarousel.itemCarousel.data('jcarousel');
                while (w + 60 + 182 < w0) {
                  w += 182;
                  ++max;
                }
                if (itemCarousel.itemCarousel.width() !== w) {
                  itemCarousel.itemCarousel.width(w);
                  jc.scroll(1);
                }
                if (itemCarousel.count <= max) {
                  jc.buttonNext.hide();
                  jc.buttonPrev.hide();
                } else {
                  jc.buttonNext.show();
                  jc.buttonPrev.show();
                }
              }

              function getItemHeights(item, forSelectable) {
                    var name1 = item.find('.pc2015-item-name');
                    var name2 = item.find('.pc2015-item-variation');
                    var name3 = item.find('.pc2015-item-catalog-price');
                    var price = item.find('.pc2015-item-price');
                    var price1 = price.eq(0);
                    var price2 = price.eq(1);
                    if (price.length === 1) {
                      price2 = null;
                    }
                    var sku = item.find('.pc2015-item-sku');
                    var inner = item.find('.pc2015-item-inner');
                    var select = item.find('.pc2015-item-select');
                    var heights = {
                      name: 0,
                      nameBottom: 0,
                      price: 0,
                      sku: 0
                    };
                    if (forSelectable) {
                      sku.css({
                        paddingBottom: 6,
                        marginBottom: 0,
                        borderBottomWidth: 0
                      });
                      select.css({
                        marginBottom: 0
                      });
                      inner.css({
                        paddingBottom: 0,
                        marginBottom: 0,
                        borderBottomWidth: 0
                      });
                    } else {
                      price1.css({
                        paddingTop: 0
                      });
                      price.last().css({
                        paddingBottom: 0,
                        marginBottom: 6
                      });
                    }
                    if (name1.length > 0) {
                      heights.name += name1.height() + 18 + 8;
                      heights.nameBottom = 8;
                    }
                    if (name2.length > 0) {
                      heights.name += name2.height() + 6;
                      heights.nameBottom = 6;
                    }
                    if (name3.length > 0) {
                      heights.name += name3.height() + 6;
                      heights.nameBottom = 6;
                    }
                    if (price1.length > 0) {
                      heights.price += price1.height();
                    }
                    if (price2) {
                      heights.price += price2.height() + 6;
                    }
                    if (sku.length > 0) {
                      heights.sku += sku.innerHeight();
                    }
                    return {
                      items: {
                        price1: price1,
                        price: price,
                        sku: sku,
                        inner: inner,
                        select: select,
                        quantity: item.find('.pc2015-item-quantity')
                      },
                      heights: heights
                    };
                  }
                function adjustItemHeight(list) {
                    var items, heights;
                    var name = 0;
                    var price = 0;
                    var sku = 0;
                    for (var l = list.length, i = 0; i < l; ++i) {
                      heights = list[i].heights;
                      name = Math.max(heights.name, name);
                      price = Math.max(heights.price, price);
                      sku = Math.max(heights.sku, sku);
                    }
                    for (i = 0; i < l; ++i) {
                      items = list[i].items;
                      heights = list[i].heights;
                      items.price1.css({
                        paddingTop: name - heights.name
                      });
                      items.price.last().css({
                        paddingBottom: price - heights.price
                      });
                      if (items.quantity.length === 0) {
                        items.price.last().css({
                          marginBottom: 59
                        });
                      }
                    }
                  }

        });
        
        function setupMainBlock(jq) {
            var block = {
                block: jq,
                header: jq.find('.pc2015-main-block-header'),
                body: jq.find('.pc2015-main-block-body'),
                visible: !jq.hasClass('pc2015-main-block-hide'),
                button: jq.find('a.pc2015-main-block-toggle')
            };
            block.button.bind('click', function () {
                if (block.visible) {
                    collapseMainBlock(block);
                } else {
                    expandMainBlock(block);
                }
                return false;
            });
            if (block.block.hasClass('pc2015-main-block-closed')) {
                collapseMainBlock(block, true);
            }
        }


        function collapseMainBlock(block, noAnimation) {
            block.visible = false;
            block.body.stop(true, true).slideUp(noAnimation ? 0 : 300, function () {
                block.block.addClass('pc2015-main-block-hide');
            });
        }

        function expandMainBlock(block, noAnimation) {
            block.visible = true;
            block.body.stop(true, true).slideDown(noAnimation ? 0 : 300, function () {
//                if (pc2015.isIE7) {
//                    block.body.find('.pc2015-center-image').each(function () {
//                        adjustCenterImageIE7($(this));
//                    });
//                }
                block.block.removeClass('pc2015-main-block-hide');
            });
        }

/**
 * js them so luong san pham vao gio hang
 * @param {type} jq
 * @param {type} noMember
 * @returns {undefined} int
 */
        function setupCartItem(jq, noMember) {
            var quantityJq = jq.find('.pc2015-cart-quantity');

            var productId = quantityJq.attr('id');
            var qty;
            jq.find('.pc2015-cart-inc').bind('click', function () {
                if (!noMember && !$(this).hasClass('pc2015-disabled')) {
                    qty = updateCartItem(quantityJq, (quantityJq.text() | 0) + 1);
                    $('#qty-' + productId).attr('value', qty);
                }
                return false;
            });

            jq.find('.pc2015-cart-dec').bind('click', function () {
                if (!noMember && !$(this).hasClass('pc2015-disabled')) {
                    qty = updateCartItem(quantityJq, (quantityJq.text() | 0) - 1);
                    $('#qty-' + productId).attr('value', qty);
                }
                return false;
            });

            jq.find('.pc2015-cart-memo').bind('click', function () {
                return false;
            });

            jq.find('.pc2015-cart-delete').bind('click', function () {
                return false;
            });
        }

/**
 * 
 * @param {type} jq
 * @param {type} quantity
 * @returns {Number} int 
 */
        function updateCartItem(jq, quantity) {
            quantity = quantity | 0;
            if (quantity < 1) {
                quantity = 1;
            } else if (quantity > 99) {
                quantity = 99;
            }
            jq.text(quantity);
            return quantity;
        }
        

    });
</script>
