
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/shop.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/common.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/reset.css') ?>"/>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Cowell_Productlist::css/aeon/etc.css') ?>"/>

<?php

/**
 * Template for displaying products list widget
 *
 * @var $block \Cowell\Productlist\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
//    $image = 'bundled_product_list_anhht'; //view.xml
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="pc2015-main-block block widget block-products-list <?php /* @escapeNotVerified */
    echo $mode; ?>">

        <!--        start header block -->
        <div class="pc2015-main-block-header">
            <h2><?php echo ($title) ? $title : '【トップバリュ 感謝の値下げ】'; ?></h2>
            <a href="#" class="pc2015-main-block-more pc2015-for-member">一覧を見る</a>
            <a href="#" class="pc2015-main-block-toggle pc2015-designed">＋</a>
        </div>
        <!--        End header block -->

        <div class="block-content pc2015-main-block-body pc2015-item-carousel jcarousel-container jcarousel-container-horizontal"
        style="position: relative; display: block;width: 899px;">
            <div class="jcarousel-clip jcarousel-clip-horizontal" style="position: relative;" >
            <?php /* @escapeNotVerified */
            echo '<!-- ' . $image . '-->' ?>
            <div class=" products-<?php /* @escapeNotVerified */
            echo $mode; ?> <?php /* @escapeNotVerified */
            echo $mode; ?>">
<!--                <img src="img/icon/00002006.jpg">-->
                <ul class="pc2015-item-list jcarousel-list jcarousel-list-horizontal <?php /* @escapeNotVerified */
                echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */
                        echo ($iterator++ == 1) ? '<li class="pc2015-item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">' : '</li><li class="pc2015-item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">' ?>
                        <div class="product-item-info">
                            <a href="<?php /* @escapeNotVerified */
                            echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name pc2015-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */
                                       echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link pc2015-item-name-title">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>


                                <?php if ($showWishlist || $showCompare || $showCart): ?>

                                <?php //$_product = $block->getProduct(); ?>
                                <div class="product-add-form">
                                <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_item) ?>" method="post" id="product_addtocart_form">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                    <input type="hidden" name="selected_configurable_option" value="" />
                                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                                    <input type="hidden" name="qty" id="qty-<?php echo $_item->getId()?>" maxlength="12" value="1" title="Qty" class="input-text">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <!-- start so luong san pham-->
                                                    <div class="control">
                                                        <dl class="pc2015-item-quantity">
                                                            <dt>数量</dt>
                                                                <dd class="pc2015-cart-quantity"
                                                                        id="<?php echo $_item->getId(); ?>"
                                                                        name="<?php echo $_item->getName(); ?>" value="" >1
                                                                </dd>
                                                        </dl>
                                                        
                                                    </div>
                                                    
                                                    <a href="javascript:void(0)" class="pc2015-designed pc2015-cart-inc">+</a>
                                                    <a href="javascript:void(0)" class="pc2015-designed pc2015-cart-dec">-</a>
                                                    <!--end so luong san pham-->

                                                    <div class="action">
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary pc2015-item-cart "
                                                                    id="product-addtocart-button"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                                    echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="submit" title="<?php /* @escapeNotVerified */
                                                            echo __('カートに入れる') ?>">
                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('カートに入れる') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            
                                                            <button type="submit" class="action tocart primary pc2015-item-cart">

                                                                <span><?php /* @escapeNotVerified */
                                                                    echo __('カートに入れる') ?></span>
                                                            </button>

                                                        <?php endif; ?>

                                                    </div>
                                                    
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                </form>
                                    </div>
                                        <a href="javascript:void(0);" class="pc2015-for-member pc2015-designed pc2015-item-memo pc2015-disabled">お買物メモに登録</a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ul>
                </div>
                
                
            </div>
            
            <?php echo $block->getPagerHtml() ?>
            <!--preview button-->
                <div class="jcarousel-prev jcarousel-prev-horizontal jcarousel-prev-disabled jcarousel-prev-disabled-horizontal" disabled="false" style=""></div>
                <!--next button-->
                <div class="jcarousel-next jcarousel-next-horizontal" disabled="false" style=""></div>   
        </div>
         
    </div>
<?php endif; ?>

<script>
    require(['jquery','jcarousel'], function ($) {
        $(function () {
            var noMember = $('body').hasClass('pc2015-no-member');
            $('.pc2015-item,.pc2015-cart-item').each(function () {
//                console.log('a-');
                setupCartItem($(this), noMember);
            });

            $('.pc2015-main-block').each(function () {
                setupMainBlock($(this));
            });
        });

        function setupCartItem(jq, noMember) {
            var quantityJq = jq.find('.pc2015-cart-quantity');

            var productId = quantityJq.attr('id');
            var qty;
            jq.find('.pc2015-cart-inc').bind('click', function () {
                if (!noMember && !$(this).hasClass('pc2015-disabled')) {
                    qty = updateCartItem(quantityJq, (quantityJq.text() | 0) + 1);
                    console.log(qty);
                    $('#qty-' + productId).attr('value', qty);
                }
                return false;
            });

            jq.find('.pc2015-cart-dec').bind('click', function () {
                if (!noMember && !$(this).hasClass('pc2015-disabled')) {
                    qty = updateCartItem(quantityJq, (quantityJq.text() | 0) - 1);
                    $('#qty-' + productId).attr('value', qty);
                }
                return false;
            });

            jq.find('.pc2015-cart-memo').bind('click', function () {
                return false;
            });

            jq.find('.pc2015-cart-delete').bind('click', function () {
                return false;
            });


        }

        function updateCartItem(jq, quantity) {
            quantity = quantity | 0;
            if (quantity < 1) {
                quantity = 1;
            } else if (quantity > 99) {
                quantity = 99;
            }
            jq.text(quantity);
            return quantity;
        }

        //
        function setupMainBlock(jq) {
            var block = {
                block: jq,
                header: jq.find('.pc2015-main-block-header'),
                body: jq.find('.pc2015-main-block-body'),
                visible: !jq.hasClass('pc2015-main-block-hide'),
                button: jq.find('a.pc2015-main-block-toggle')
            };
            block.button.bind('click', function () {
                if (block.visible) {
                    collapseMainBlock(block);
                } else {
                    expandMainBlock(block);
                }
                return false;
            });
            if (block.block.hasClass('pc2015-main-block-closed')) {
                collapseMainBlock(block, true);
            }
        }


        function collapseMainBlock(block, noAnimation) {
            block.visible = false;
            block.body.stop(true, true).slideUp(noAnimation ? 0 : 300, function () {
                block.block.addClass('pc2015-main-block-hide');
            });
        }

        function expandMainBlock(block, noAnimation) {
            block.visible = true;
            block.body.stop(true, true).slideDown(noAnimation ? 0 : 300, function () {
                if (pc2015.isIE7) {
                    block.body.find('.pc2015-center-image').each(function () {
                        adjustCenterImageIE7($(this));
                    });
                }
                block.block.removeClass('pc2015-main-block-hide');
            });
        }

        function adjustCenterImageIE7(centerImage) {
            centerImage.find('img').each(function () {
                $(this).css({
                    left: '50%',
                    right: 'auto',
                    top: '50%',
                    bottom: 'auto',
                    marginRight: 0,
                    marginBottom: 0,
                    marginLeft: Math.round(this.width / -2),
                    marginTop: Math.round(this.height / -2)
                });
            });
        }

        //
        (
            function ($, pc2015) {
                'use strict';
                if (!$ || !pc2015) return;
                var sliderButton = '<a href="#" class="pc2015-designed"></a>';

                function setupSlider(jq) {
                    var slider = {
                        base: jq,
                        headers: jq.find('.pc2015-main-slider-header > li'),
                        items: jq.find('.pc2015-main-slider-body > ul > li'),
                        slider: jq.find('.pc2015-main-slider-body')
                    };
                    slider.slider.jcarousel({
                        scroll: 1,
                        auto: 10,
                        wrap: 'circular',
                        buttonPrevHTML: sliderButton,
                        buttonNextHTML: sliderButton,
                        setupCallback: function () {
                            slider.slider.find('.jcarousel-prev,.jcarousel-next').bind('click', function () {
                                return false;
                            });
                            updateSliderHeader(slider, 0);
                        },
                        itemFirstInCallback: {
                            onBeforeAnimation: function (jc, li) {
                                if (pc2015.isIE7) {
                                    li = $(li);
                                    var a = $(li).find('a');
                                    if (a.length === 0) {
                                        a = slider.items.eq((jc.first - 1) % slider.headers.length).find('a').clone(false);
                                        li.append(a);
                                    }
                                }
                            },
                            onAfterAnimation: function (jc, li) {
                                updateSliderHeader(slider, jc.first - 1);
                            }
                        }
                    });
                    slider.headers.each(function (i) {
                        $('a', this).bind('click', function () {
                            slider.slider.data('jcarousel').scroll(i + 1);
                            return false;
                        });
                    });
                }

                function updateSliderHeader(slider, i) {
                    var headers = slider.headers;
                    headers.removeClass('pc2015-active').eq(i % headers.length).addClass('pc2015-active');
                }

                $('.pc2015-main-slider').each(function () {
                    setupSlider($(this));
                });


            });
    })
</script>